# The public documentation URL, used for sitemap.xml
url: "https://docs.telerik.com/fiddler-jam"

# Exclude files which should not be in the output
exclude: [README.md, Gemfile, Gemfile.lock]
exclude_navigation: ["knowledge-base/*"]

## List your directory names and order here, like this:
navigation:
    fj-extension:
        title: Chrome Extension
        position: 10
    portal:
        title: Fiddler Jam Portal
        position: 20
## Product title
product: "Progress Telerik Fiddler Jam"
platform: fiddler-jam

## An experimental property to resolve the SEO vs STA panels conflicts discussed in the following issue: https://github.com/telerik/docs-seed/issues/159
## Use only with docs-seed branch #fiddler-page-title
page_title_product: "Fiddler Jam"
use_product_in_title: true

## The application virtual path
baseurl: /fiddler-jam

## Assign layout and category per different paths
defaults:
-
    scope:
        path: ""
    values:
        layout: "documentation"
        category: "default"
        product: "fiddler"
        editable: true
        announcementUrl: "https://docs.telerik.com/kendo-api/announcements/fiddler-jam"

has_kb_portal: false
has_api_reference: false

# Feedback Form ID generated on 26th of January 2021 (by TM)
ff-sheet-id: 3e851bb4-5930-46e5-98d6-4fda8cd0bcc9

# The google services configuration
google_analytics: UA-111455-1
google_tag_manager: GTM-6X92
gcs_engine: '752200f3728b3d92f'
gcs_api_key: 'AIzaSyDb6GdIgfIVlHubf-i0CpahRjtkCz9o6cE'

hide_contact_support: true
edit_repo_url: https://github.com/telerik/fiddler-jam-docs/edit/master
download: https://chrome.google.com/webstore/detail/fiddler-jam/fnkjlegmkbicdodlheligomlfbdblpfj
nav:
  "What's New": https://www.telerik.com/support/whats-new/fiddler-jam
  "Release History": https://www.telerik.com/support/whats-new/fiddler-jam/release-history
  "About": https://www.telerik.com/fiddler-jam

footer:
-
  title: "Getting Started"
  links:
    "First Steps with Fiddler Jam Chrome Extension": https://docs.telerik.com/fiddler-jam/fj-extension/get-started-extension.html
    "First Steps with Fiddler Jam Portal": https://docs.telerik.com/fiddler-jam/portal/get-started-portal.html
    "Download Fiddler Jam Extension Now": https://chrome.google.com/webstore/detail/fiddler-jam/fnkjlegmkbicdodlheligomlfbdblpfj
    "License": https://www.telerik.com/purchase/license-agreement/fiddler-jam
-
  title: "Support Resources"
  links:
    "Fiddler Webinars": https://www.telerik.com/webinars/fiddler-jam
    "What's New": https://www.telerik.com/support/whats-new/fiddler-jam
    "Roadmap": https://www.telerik.com/support/whats-new/fiddler-jam/roadmap
    "Release History": https://www.telerik.com/support/whats-new/fiddler-jam/release-history

-
  title: "Community"
  links:
    "All Things Fiddler": https://www.telerik.com/blogs/fiddler
    "Fiddler Videos": https://www.telerik.com/videos/fiddler/tag/fiddler-jam
    "Fiddler Forums": https://community.getfiddler.com/support/discussions
    "Fiddler Blogs": https://www.telerik.com/blogs/tag/fiddler-jam


footer_social:
    facebook: https://www.facebook.com/Telerik/
    youtube: https://www.youtube.com/user/TelerikInc
    linkedin: https://www.linkedin.com/showcase/telerik/
    twitter: https://twitter.com/TelerikFiddler/


# TEMP


# Assets pipeline configuration
assets:
    cachebust: soft
    js_compressor: uglifier

## Do not edit below this line
safe: false
markdown: MarkdownProcessor
kramdown:
    toc_levels: 2..3
    smart_quotes: ["quot", "quot", "quot", "quot"]
    input: GFM
